### ISSUE TITLE
DCPError: in finite_outcome

### ISSUE THREAD

**Issue by giamp66** [cvxgrp/kelly_code#1]
Hello,
running the finite_outcome notebook I get an DCPError in cell "Table RCK".

I use:
ubuntu 16.4 LTS;
Python 2.7.11 :: Anaconda 4.0.0 (64-bit);
cvxpy                     0.4.8 (from Github repo )

Where  am I wrong?
Thanks.
Gianpaolo Galli

**Comment by ghost** [comment]
that is likely a cvxpy bug, i never observed it. can you install cvxpy from a standard package (i.e., anaconda?)

**Comment by ghost** [comment]
this is the cvxpy install guide http://www.cvxpy.org/en/latest/install/index.html

**Comment by ghost** [comment]
also (orthogonally) can you please post the full stack trace?

**Comment by giamp66** [comment]
here the traceback
---------------------------------------------------------------------------
DCPError                                  Traceback (most recent call last)
<ipython-input-6-f6d4d6360581> in <module>()
      2 for lambda_rck.value in [0, log(betagg)/log(alpha), 5.5]:
      3     print '%.3f '% lambda_rck.value,
----> 4     probl_rck.solve()
      5     exp_growth_rate, W_mins = growth_rate_Wmins(
      6         simulate_trajectories(np.reshape(mc_sample.T, (MC_N_SAMPLES, MC_T, n)), 

/home/giamp/anaconda2/lib/python2.7/site-packages/cvxpy/problems/problem.pyc in solve(self, *args, **kwargs)
    208             return func(self, *args, **kwargs)
    209         else:
--> 210             return self._solve(*args, **kwargs)
    211 
    212     @classmethod

/home/giamp/anaconda2/lib/python2.7/site-packages/cvxpy/problems/problem.pyc in _solve(self, solver, ignore_dcp, warm_start, verbose, parallel, **kwargs)
    282                       "Solving a convex relaxation.")
    283             else:
--> 284                 raise DCPError("Problem does not follow DCP rules.")
    285 
    286         if solver == s.LS:

DCPError: Problem does not follow DCP rules.

the problem is in risk_constraint in fact I obtain:
 ('risk_constraint.is_dcp()', False)

**Comment by giamp66** [comment]
on Windows 7 Home premium
with python(x,y) installed and cvxpy version '0.2.24'
it works if I use solver = 'SCS' otherwise it says :
SolverError: Solver 'XXX' failed. Try another solver.
where XXX is for ['CVXOPT', 'ECOS_BB', 'GLPK_MI',  'ECOS', 'GLPK']

It's seams to be a 0.4.8 cvxpy versione problem

**Comment by ghost** [comment]
i looked into that, it looks like it is a bug in cvxpy

@SteveDiamond, can you have a look?

in the meantime you can disable DCP check by using

`problem.solve(ignore_dcp=True)
`

**Comment by giamp66** [comment]
In solving a convex relaxation it gives the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-2426ad94e3e0> in <module>()
      5     exp_growth_rate, W_mins = growth_rate_Wmins(
      6         simulate_trajectories(np.reshape(mc_sample.T, (MC_N_SAMPLES, MC_T, n)), 
----> 7                               b_rck.value.A1))
      8     print '& %.3f '% (exp_growth_rate),
      9     print '& %.3f '% (exp(lambda_rck.value * log(alpha))),

AttributeError: 'NoneType' object has no attribute 'A1'
```

**Comment by SteveDiamond** [comment]
It looks like you forgot to initialize a parameter. By the way, I fixed the
bug you found with DCP in cvxpy on the master branch.

**Comment by giamp66** [comment]
Now it works perfectly, 
thank you all very much.
